"""empty message

Revision ID: 4b8f30053fc6
Revises: c20748132f3a
Create Date: 2017-04-19 07:28:57.446091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8f30053fc6'
down_revision = 'c20748132f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataserver', sa.Column('datacenter_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'dataserver_dataserver_id_fkey', 'dataserver', type_='foreignkey')
    op.create_foreign_key(None, 'dataserver', 'datacenter', ['datacenter_id'], ['id'])
    op.drop_column('dataserver', 'dataserver_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataserver', sa.Column('dataserver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dataserver', type_='foreignkey')
    op.create_foreign_key(u'dataserver_dataserver_id_fkey', 'dataserver', 'dataserver', ['dataserver_id'], ['id'])
    op.drop_column('dataserver', 'datacenter_id')
    # ### end Alembic commands ###
